config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }
  root 'welcome#index'
  get '/', to: 'welcome#index'
  get '/success', to: 'welcome#success'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/users', to: 'users#list'
  #resources :users
  resources :posts
  get '/blog', to: 'posts#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:yahoo]



  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.yahoo_data"] && session["devise.yahoo_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # user.email = auth.info.email
      # user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end

    Reach back out to PS and see if he can provide any information backing this as a general Matrix thing.
        Especially looking for network diagnostics and if he sees an uptick in these issues at a specific date/time. Then reach back out to PI w/ that data, and include PS dude on it.

        Check historical data (Newrelic maintains a few weeks) and see when this started (exact time too), then reach out to Jobs Development and see if they can take a look at the read timeouts for search/details, especially if there were any changes made at that time.

    @token = auth["credentials"]["token"]

    binding.pry
    week_number = 1
    team = 4
    scoreboard_url = "https://fantasysports.yahooapis.com/fantasy/v2/league/359.l.101698/scoreboard;week=#{ week_number }"
    players_url =  "https://fantasysports.yahooapis.com/fantasy/v2/team/359.l.101698.t.#{ team }/players"
    roster_per_week = "https://fantasysports.yahooapis.com/fantasy/v2/team/359.l.101698.t.9/roster;week=10"

    # query = {
    #     "method"     => "neworder",
    #     "nonce"      => 1404996028,
    #     "order_type" => "buy",
    #     "quantity"   => 1,
    #     "rate"       => 1
    # }
    headers = {
        "Authorization"  => "Bearer #{ @token }",
        "sign" => "0a3888ac7f8e411ad73a0a503c55db70a291bfb9f9a47147d5200882674f717f6ede475669f3453"
    }

    response =HTTParty.get(
        "https://fantasysports.yahooapis.com/fantasy/v2/team/359.l.101698.t.#{ team }/players",
        :headers => headers)

    File.open("data/rosters/2016/2016_roster_#{ team }.json", 'w') do |f|
      f.puts response.to_json
    end

    # while team < 11 do
    #   response =HTTParty.get(
    #       "https://fantasysports.yahooapis.com/fantasy/v2/team/359.l.101698.t.#{ team }/players",
    #       :headers => headers)
    #
    #   File.open("data/rosters/2016/2016_roster_#{ team }.json", 'w') do |f|
    #     f.puts response.to_json
    #   end
    #   team += 1
    # end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  # has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def yahoo
    # You need to implement the method below in your model (e.g. app/models/admin.rb)
    @token = Admin.from_omniauth(request.env["omniauth.auth"])['token']


    redirect_to '/blog'


    # if @admin.persisted?
    #   sign_in_and_redirect @admin, :event => :authentication #this will throw if @admin is not activated
    #   set_flash_message(:notice, :success, :kind => "Yahoo") if is_navigational_format?
    # else
    #   session["devise.yahoo_data"] = request.env["omniauth.auth"]
    #   redirect_to new_admin_registration_url
    # end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @posts = Post.all
    # @yahoo = yahoo
  end

  def omniauth_callbacks

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post."
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating post."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post."
      redirect_to post_path(@posts)
    else
      flash[:alert] = "Error updating post."
      render :edit
    end
  end

  def show
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Successfully Deleted post."
      redirect to posts_path
    else
      flash[:alert] = "Error deleting post."
    end
  end

  private

  def yahoo
    oauth_client = OAuth2::Client.new(ENV['YAHOO_CLIENT'], ENV['YAHOO_SECRET'], {
        site: 'https://api.login.yahoo.com',
        authorize_url: '/oauth2/request_auth',
        token_url: '/oauth2/get_token',
    })


    auth = "Basic #{Base64.strict_encode64("#{ENV['YAHOO_CLIENT']}:#{ENV['YAHOO_SECRET']}")}"


    new_token = oauth_client.get_token({
                                           redirect_uri: 'http://www.devstart.co',
                                           refresh_token: YOUR_REFRESH_TOKEN,
                                           grant_type: 'refresh_token',
                                           headers: { 'Authorization' => auth } })
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/success'
    else
      flash[:error] = "There was an Error Saving your submission. Please resubmit with Name and Email."
      redirect_to '/'
    end
  end

  def list
    @users = User.find_each
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :age, :number_of_children,
                                 :location, :preferred_day, :course_preference, :comments)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end

  def success
    render 'successful_signup'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Dev Start | Professionals Teaching Young Adults Software" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <%= favicon_link_tag 'devstartfav.ico' %>
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.haml
= javascript_include_tag Ckeditor.cdn_url

= form_for @post do |f|
  = f.label :title, 'Title of Post:'
  = f.text_field :title
  %br/
  = f.label :body, 'Body:'
  = f.cktext_area :body
  %br/
  = f.submit

app/views/posts/index.haml
-#%li= link_to 'Logout', destroy_admin_session_path, :method => :delete
%li= link_to 'Sign in with Yahoo', admin_yahoo_omniauth_authorize_path
.row
  .small-12.columns
    - @posts.each do |post|
      .post
        = "Title: #{ post.title }"
        = post&.body&.html_safe

app/views/posts/new.haml
.row
  .small-12.columns
    %h1
      Create a new blog post
    = render partial: 'form'

app/views/shared/_error_messages.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/users/list.haml
.row
  .small-12.columns
    %h1
      Users Stats:
    %p
      = "Total Users: #{ @users.count }"
    %hr
    = @users.each do |u|
      %h2
        = "User #{ u.id }"
      %p
        = "Name: #{ u.name }"
        %br
        = "Email: #{ u.email }"
        - unless u.number_of_children.blank?
          %br
          = "number_of_children: #{ u.number_of_children }"
        - unless u.age.blank?
          %br
          = "age: #{ u.age }"
        - unless u.location.blank?
          %br
          = "location: #{ u.location }"
        - unless u.phone_number.blank?
          %br
          = "phone_number: #{ u.phone_number }" unless u.phone_number.blank?
        - unless u.preferred_day.blank?
          %br
          = "preferred_day: #{ u.preferred_day }" unless u.preferred_day.blank?
        - unless u.course_preference.blank?
          %br
          = "course_preference: #{ u.course_preference }" unless u.course_preference.blank?
        - unless u.comments.blank?
          %br
          = "comments: #{ u.comments }" unless u.comments.blank?

app/views/users/new.haml
.row
  .small-12.columns
    = form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Create my account", class: "btn btn-primary"

app/views/welcome/index.haml
.nav-bar
  .row
    .small-8.medium-3.columns
      = image_tag("DevStart-Logo.svg")
    .small-4.medium-4.medium-offset-5.columns.button-container
      .button.round.success.modal-click
        Sign Up Now!
.hero-image
  .row
    .small-12.columns
      %h2
        Introducing
      %h1
        DEV START
      %p
        Affordable and Professional Computer Programming Training for Young Adults in John's Creek.
.pitch
  .row
    .small-12.columns
      = image_tag("DevStart-Logo-notext.svg")
    .small-12.medium-8.medium-offset-2.end.columns
      %p.pitch-text
        Would you rather have a professional bodybuilder be your personal trainer or somebody who earned their certification online?
        We believe the same should go for learning how to program. Dev Start is a team of professionals who are ready to prepare your children for a career in programming.
      %p.starting-date
        Starting June 17th at the John's Creek Arts Center!
.courses
  .row.course-intro
    .small-12.medium-8.medium-offset-2.end.columns
      %h3
        Course Information & Pricing
      %p
        We focus on Scratch, the programming language developed at the MIT Media Lab. With Scratch, you can program your own interactive stories, games, and animations — and share your creations with others in the online community. Scratch helps young people learn to think creatively, reason systematically, and work collaboratively — essential skills for life in the 21st century.
  .row.course-descriptions
    .small-12.medium-6.columns
      = image_tag("FutureEngineer-Illustration.svg")
      %h5
        Future Engineer (6 weeks)
      .money
        %span.money-strike
          $500
        &nbsp;&nbsp;$300
      %p
        Over the course of 6 weeks, develop a great understanding of Programming through Scratch and create numerous projects to show off what you have learned.
        You will have the experience and preparation necessary to tackle languages such as Python or Javascript.
    .small-12.medium-6.columns
      = image_tag("HelloWorld-Illustration.svg")
      %h5
        Hello World! (2 weeks)
      .money
        $150
      %p
        Over the course of 2 weeks, receive a basic understanding of Programming through Scratch and what you are capable of accomplishing with it. Build a small scratch program to show off what you have learned.
    .small-12.columns
      .button.round.success.modal-click
        Sign Up For A Course!
.benefits
  .row
    .small-12.medium-4.columns
      = image_tag("ProfessionalInstructors-Illustration.svg")
      %h5
        Professional Instructors
      %p
        Learning how to program from professionals will properly prepare you for software development in the real world. We are a team of software engineers with computer science backgrounds who currently work for Careerbuilder. We have a passion for building great software and want to inspire the next generation of engineers and programmers.
    .small-12.medium-4.columns
      = image_tag("ExcellentEducation-Illustration.svg")
      %h5
        Excellent Education
      %p
        Learning how to program from professionals will properly prepare you for software development in the real world. We are a team of software engineers with computer science backgrounds who currently work for Careerbuilder. We have a passion for building great software and want to inspire the next generation of engineers and programmers.
    .small-12.medium-4.columns
      = image_tag("AffordableDependable-Illustration.svg")
      %h5
        Affordable & Dependable
      %p
        Learning how to program from professionals will properly prepare you for software development in the real world. We are a team of software engineers with computer science backgrounds who currently work for Careerbuilder. We have a passion for building great software and want to inspire the next generation of engineers and programmers.
    .small-12.columns
      .button.round.see-through.modal-click
        Contact Us For More Info
.team
  .row
    .small-12.columns
      %h3
        Meet The Team
    .small-12.medium-4.columns
      = image_tag("https://s3.amazonaws.com/media.launchrock.com/assets/sites/site-ez6ps65061biekqm3zigtpokn/x5ysbh-bradimage3.jpg")
      %p
        Brad is a software engineer for Careerbuilder. He received his undergraduate from the University of North Georgia.
        He has experience with Ruby on Rails, C#, and AWS.
    .small-12.medium-4.columns
      = image_tag("https://s3.amazonaws.com/media.launchrock.com/assets/sites/site-ez6ps65061biekqm3zigtpokn/74hh3e-yudiimage.jpg")
      %p
        Yudi is a software engineer for Careerbuilder. He received his undergraduate from the University of Alabama.
        He is currently pursuing his masters degree in computer science from Georgia Tech.
    .small-12.medium-4.columns
      = image_tag("https://s3.amazonaws.com/media.launchrock.com/assets/sites/site-ez6ps65061biekqm3zigtpokn/0xqzaw-naveenimage.jpg")
      %p
        Naveen is a mobile apps software engineer for Careerbuilder. He received his undergraduate from Georgia Tech and is
        currently one of two engineers who maintain and build the Careerbuilder apps for both IOS and Android.
.map
  .small-12.medium-3.medium-offset-1.columns
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "350", :src => "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13223.829529443536!2d-84.1758161!3d34.0449643!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x4620936c4b877464!2sJohns+Creek+Arts+Center!5e0!3m2!1sen!2sus!4v1495596077962", :style => "border:0", :width => "600"}
  .small-10.small-offset-1.medium-4.medium-offset-4.end.columns
    .row
      = form_for(@user, url: signup_path) do |f|
        .small-12.columns
          = render 'shared/error_messages'
        .small-12.input-field.columns
          = '*Your Name'
          = f.text_field :name, class: 'form-control'
        .small-12.input-field.columns
          = '*Email'
          = f.email_field :email, class: 'form-control'
        .small-12.input-field.columns
          = 'Phone Number'
          = f.phone_field :phone_number, class: 'form-control'
        .small-12.columns.sign-up
          = f.submit "Sign Up Now!", class: "button round success full-width"
  .small-12.columns
    %p.contact-us
      Contact us at any time by emailing us at
      %a{:href => "mailto:support@devstart.co", :target => "_top"} support@devstart.co
    #myModal.modal
      .small-12.medium-8.medium-centered.columns
        .row.modal-content
          %span.close ×
          = form_for(@user, url: signup_path) do |f|
            .small-12.columns
              = render 'shared/error_messages'
            .small-12.input-field.columns
              = '*Your Name'
              = f.text_field :name, class: 'form-control'
            .small-12.input-field.columns
              = '*Email'
              = f.email_field :email, class: 'form-control'
            .small-12.input-field.columns
              = 'Phone Number'
              = f.phone_field :phone_number, class: 'form-control'
            .small-12.columns.sign-up
              = f.submit "Sign Up Now!", class: "button round success full-width"

app/views/welcome/successful_signup.haml
.successful-signup
  .row
    .small-10.small-centered.columns
      .row
        .small-3.show-for-small-only.end.columns#top-image
          = image_tag("https://www.thehvca.co.uk/wp-content/uploads/2017/03/rocket-icon.png")
      .row
        .small-12.columns.show-for-small-only
          %h3
            Thank you for your interest in
          %h1
            Dev Start!
        .small-7.hide-for-small-only.columns
          %h3
            Thank you for your interest in
          %h1
            Dev Start!
        .small-3.hide-for-small-only.columns#image
          = image_tag("https://www.thehvca.co.uk/wp-content/uploads/2017/03/rocket-icon.png")
  .row
    .small-10.small-centered.columns
      %hr
        %p
          We are so excited to begin this adventure with you and your child.
          We both want your child to be the absolute best programmer possible.
          We will email you as soon as we have reviewed your submission with
          further information regarding upcoming classes.
      =link_to('Back to Homepage', '/', class: 'button')